sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t hnakamur/libvmodvslprpm .

script:
  - docker run hnakamur/libvmodvslprpm "$COPR_LOGIN" "$COPR_USERNAME" "$COPR_TOKEN"
